dist: xenial

language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"

install:
  - pip install -r ./requirements.txt
  - pip install -e .

script:
  - flake8 --config=./.flake8rc django_iban_field
  - coverage run --source=django_iban_field ./manage.py test
  - coverage report -m

after_success:
  - coveralls
